version: '3'
services:
  dump1090:
    image: "jraviles/dump1090:latest"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: always
    networks:
      adsb:
        aliases:
          - dump1090
  adsbcot:
    image: "adsbcot:latest"
    build: "./adsbcot"
    expose:
      - 8080
      - 8089
    ports: 
      - "8089:8089"
    restart: always
    volumes:
      - type: bind
        source: ./adsbcot/certs/
        target: /app/
    environment:
    # - e.g. tls://cotserver.com:1234
      - COT_URL=<tls or tcp>://<hostname for CoT server>:<Secure CoT server port number>
      - DUMP1090_URL=http://dump1090:8080/data/aircraft.json
      # Poll rate for dump1090, in seconds
      - POLL_INTERVAL=1
      # Not required if using TCP connectivity
      - PYTAK_TLS_CLIENT_CERT=/app/<guest certificate>.pem
      - PYTAK_TLS_CLIENT_KEY=/app/<guest certificate key>.key
      - PYTAK_TLS_CLIENT_CAFILE=/app/<server CA truststore>.pem
      # Hack because of self-signed cert in CA file
      - PYTAK_TLS_DONT_VERIFY=true
    networks:
      adsb:
        aliases:
          - adsbcot
networks:
  adsb: